import './globals.css'
import '@fortawesome/fontawesome-free/css/all.css';

import Footer from 'src/Components/Footer.tsx'
import Head from 'next/head'
import Header from '../components/Header.tsx'
import { Inter } from 'next/font/google'
import type { Metadata } from 'next'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Nexusdairy',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
    <Head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"></link>
    </Head>
      <body className={inter.className}>
        <Header /> 
        <div style={{ height: '60px' }}></div>
        
        {children}
        <Footer />
      </body>
    </html>
  )
}

